name: Authoring and Debugging

# on: [pull_request, workflow_dispatch]
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: |
          echo "Workflow triggered in branch '${{ github.ref }}'."
          echo "Workflow triggered by event '${{ github.event_name }}'."
          echo "Workflow triggered by actor '${{ github.actor }}'."

      - uses: actions/checkout@v4.1.5
      - run: |
          echo "::debug::This is a debug message."
          echo "::notice::This is a notice message."
          echo "::warning::This is a warning message."
          echo "::error::This is an error message."

      - run: |
          echo "::notice file=.github/workflows/02_debug.yml,line=19,col=11,endColumn=51::There is a debug message that is not always visible!"
          echo "::warning file=.github/workflows/02_debug.yml,line=19,endline=21::A lot of messages"
          echo "::error title=Script Injection,file=.github/workflows/02_debug.yml,line=13,col=37,endColumn=68::Potentialscript injection"

      - uses: devops-actions/actionlint@v0.1.2

      - run: echo "${{ github.event.pull_request.title }}"

      - run: echo "PR title is '${{ github.event.pull_request.title }}'."
