name: Android CD/CD

on:
  workflow_run:
    workflows: ["android ci"]
    types:
      - completed

jobs:
  apk:
    name: Build Release signed APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
