name: Android CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.5
    - run: tree
    - name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - run: |
        echo "Hello ${{ vars.WHO_TO_GREET }} 👋 from ${{ github.actor }}."
        echo "My secret is 🤫 ${{ secrets.MY_SECRET }}."

    - name: Grant gradlew permission
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Setup JAVA 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant gradlew permission
        run: chmod +x gradlew
      - name: Run lint
        run: ./gradlew lintDebug
      - name: Run Unit Test
        run: ./gradlew test
